apiVersion: v1
kind: PersistentVolume
metadata:
  name: volworker-03-csi
  namespace: vault
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local-vault-csi-storage
  local:
    path: /srv/cluster/storage/vault-ha-csi
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - k8snode01.mylab.io

--- 
apiVersion: v1
kind: PersistentVolume
metadata:
  name: volworker-04-csi
  namespace: vault
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local-vault-csi-storage
  local:
    path: /srv/cluster/storage/vault-ha-csi
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - k8snode02.mylab.io

