apiVersion: v1
kind: PersistentVolume
metadata:
  name: volworker-03-csi
  namespace: vault
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local-vault-csi-storage
  local:
    path: /srv/cluster/storage/vault-ha-csi

--- 
apiVersion: v1
kind: PersistentVolume
metadata:
  name: volworker-04-csi
  namespace: vault
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local-vault-csi-storage
  local:
    path: /srv/cluster/storage/vault-ha-csi
