global:
   imagePullSecrets:
   - name: regcred
   enabled: true
   tlsDisable: true
injector:
   enabled: false
#   image:
#     repository: "registry.connect.redhat.com/hashicorp/vault-k8s"
#     tag: "latest"
#   agentImage:
#     repository: "registry.connect.redhat.com/hashicorp/vault"
#     tag: "latest"

csi:
  enabled: true

server:
   image:
     repository: "registry.connect.redhat.com/hashicorp/vault"
     tag: "latest"
   standalone:
      enabled: false
   affinity: ""
   dataStorage:
     storageClass: local-vault-csi-storage
   ha:
      enabled: true
      replicas: 2
      raft:
         enabled: true
         setNodeId: true
         config: |
            cluster_name = "vault-csi-integrated-storage"
            ui = true
            listener "tcp" {
               tls_disable = "true"
               address = "[::]:8200"
               cluster_address = "[::]:8201"
            }
            storage "raft" {
               path = "/vault/data"
               retry_join {
                 leader_api_addr = "http://argo-vault-csi-0.argo-vault-csi-internal:8200"
               }
               retry_join {
                 leader_api_addr = "http://argo-vault-csi-1.argo-vault-csi-internal:8200"
               }
            }
            disable_mlock = true
            service_registration "kubernetes" {}
# Vault UI
ui:
  enabled: true
  serviceType: "LoadBalancer"
  serviceNodePort: null
  externalPort: 80 # Changed from 8200 to 443
