apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: mysql-db
spec:
  provider: vault
  secretObjects:
    - secretName: mysql-db-secret
      type: Opaque
      data:
        - objectName: dbPassword
          key: password
  parameters:
    vaultAddress: "https://argo-vault-csi-internal.vault-csi-argocd:8200"
    roleName: 'mysql-role'
    vaultSkipTLSVerify: "true"
    objects: |
      - objectName: "dbPassword"
        secretPath: "secret/data/database/mysql"
        secretKey: "password"
